[package]
name = "rust_oss_template"
version = "0.1.0"
authors = ["Chris Ohk <utilForever@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
