name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cargo build
      run: cargo build --all
    - name: Cargo test
      run: cargo test --all
    - name: Run Rustfmt
      run: cargo fmt --all -- --check
